name: MT API Tests
env:
  API_BASE_URL: http://localhost:3000
  ENVIRONMENT: dev
on:
  push:
    branches:
      - topic/MT_UsersTests
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start application
        run: |
          docker run -d \
            --name sdet-challenge \
            -p 3000:3000 \
            ghcr.io/danielsilva-loanpro/sdet-interview-challenge:latest
      
      - name: Check container
        run: |
            echo "Container status:"
            docker ps -a

            echo "Container logs:"
            docker logs sdet-challenge

      - name: Wait for API
        run: |
          echo "Waiting for API..."

          for i in {1..30}; do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/dev/users | grep -q "200\|404"; then
              echo "API is ready!"
              exit 0
            fi

            echo "Attempt $i - API not ready yet..."
            sleep 2
          done

          echo "API failed to start"
          docker logs sdet-challenge
          exit 1

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./LP-UserManagementTests

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./LP-UserManagementTests

      - name: Run API tests
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./TestResults

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: TestResults/

      - name: Docker logs
        if: failure()
        run: docker logs sdet-challenge

      - name: Stop application
        if: always()
        run: docker stop sdet-challenge
